DROP TABLE IF EXISTS MANUFACTURER;
DROP TABLE IF EXISTS CAR;

CREATE TABLE MANUFACTURER(ID IDENTITY NOT NULL PRIMARY KEY, NAME VARCHAR(50), COUNTRY VARCHAR(50), YEAR INT(4))
    AS SELECT NULL, * FROM CSVREAD('classpath:manufacturers.csv');

CREATE TABLE CAR(ID IDENTITY NOT NULL PRIMARY KEY, `MODEL YEAR` INT(4), DIVISION VARCHAR(50), CARLINE VARCHAR(50),
`ENG DISPL` VARCHAR(50),`# CYL` VARCHAR(50),`CITY FE` VARCHAR(50),`HWY FE` VARCHAR(50), `COMB FE` VARCHAR(50))
    AS SELECT NULL, * FROM CSVREAD('classpath:fuel.csv');